### ISSUE TITLE
Issue with converting mph to km/h

### ISSUE THREAD

**Issue by bsrishi** [tlskinneriv/awnet_local#13]
Hi @tlskinneriv,

The latest update works like a charm. But, however, just a couple of sensors are having issues with the unit conversion to km/h.

*Wind Speed
*Max Gust

These both sensors, don't change to km/h even if you try changing in the UI.

Please assist.

Thanks,
Rishi B S

**Comment by tlskinneriv** [comment]
What version of HA are you running? The latest update (v0.3.0) was tested with 2023.1. Where are you trying to change the unit?

Where I was able to change the value and validate that the conversion occurred was in the entity settings UI (click entity in UI, click the "Settings" tab, then change "Unit of Measurement" to "km/h"). On the next state update the value was converted.

Screenshot of settings page:

![image](https://user-images.githubusercontent.com/14053273/211025698-33972463-62b1-40e6-97ff-6bdbee1b959b.png)

Screenshot of entity with changed unit in Lovelace:

![image](https://user-images.githubusercontent.com/14053273/211026040-60da19c3-a4ce-4c25-9d86-b88670ef3dbd.png)

That particular value is shown for when the device sent exactly 1.0 mph as the value

**Comment by bsrishi** [comment]
My bad, forgot to remove the code in customize.yaml, the one I had a seperate sensor added and unit of measurement defined.

Kudos. Working great

**Comment by bsrishi** [comment]
Hourly Rain rate alone comes only in "in/h". Irrespective of whatever value I convert.

Please check this

**Comment by tlskinneriv** [comment]
Looks like there may not be a built-in conversion for that unit in HA currently. It appears that the `UnitOfVolumetricFlux` unit enum is not currently covered in HA [unit_system.py](https://github.com/home-assistant/core/blob/d4f69a365291f8dad3e05fc0912578fffc12373c/homeassistant/util/unit_system.py). Will take a look at this later and see what can be done.

**Comment by tlskinneriv** [comment]
Looks like both `UnitOfVolumetricFlux` and `UnitOfIrradiance` are the units that are unable to be converted at this time automatically via HA.

**Comment by bsrishi** [comment]
Oh okay ! And just noticed that Feels like temperature is missing for the indoor and additionally added units but available on AWN.

**Comment by tlskinneriv** [comment]
Please open a new feature request for these extra sensors. Thanks!

**Comment by tlskinneriv** [comment]
Closing this issue since `UnitOfVolumetricFlux` and `UnitOfIrradiance` are not supporting conversion in HA yet. Not something to be done in this integration and will work when HA supports it. Looks like `UnitOfVolumetricFlux` will be supported in 2023.3. I see no implementation of conversion for `UnitOfIrradiance` in [unit_conversion.py](https://github.com/home-assistant/core/blob/dev/homeassistant/util/unit_conversion.py) yet, which would be required to use it in [unit_system.py](https://github.com/home-assistant/core/blob/dev/homeassistant/util/unit_system.py).
