### ISSUE TITLE
2023.3 Update - Log Warning for async_setup_platforms instead of async_forward_entry_setups

### ISSUE THREAD

**Issue by ziptbm** [tlskinneriv/awnet_local#18]
**Describe the bug**
After upgrading to 2023.3, I'm seeing this warning in my logs for this integration

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: March 1, 2023 at 18:20:51 (1 occurrences)
Last logged: March 1, 2023 at 18:20:51

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for awnet_local using this method at custom_components/awnet_local/__init__.py, line 109: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
```

**To Reproduce**
I've done nothing since original installation other than upgrade Home Assistant to the latest version.

**Expected behavior**

I'd like to understand if this impacts anything or if I need to take action on my end to fix.

**Comment by tlskinneriv** [comment]
Cause: deprecated method
Impact: integration will potentially fail to load
