### ISSUE TITLE
co2_battery  - I don't have this, but it shows up as an entity also missing wx station battery

### ISSUE THREAD

**Issue by heyitsyang** [tlskinneriv/awnet_local#25]
**Integration Version**:  v1.1.1

**Home Assistant Version**: 2023.5.4

**Describe the bug**
I have the WS-2902A integrated into HA.  As far as I know, I don't have a CO2 sensor, yet co2_battery shows up as a binary_sensor entity.  I also cannot find the binary_sensor entity for the weather station battery.

**To Reproduce**
I haven't done anything but install your awnet add-on fork and awnet_local integration.

**Expected behavior**
Expect to find the weather station battery entity and not the co2 sensor entity.

**Screenshots**

**Additional context**

**Debug log output from the integration (see Home Assistant docs for how to enable debug logging for an integration; integration name: "custom_components.awnet_local")**
```
Paste your logs here
```

**Comment by tlskinneriv** [comment]
Detected battery sensors should show up in the Diagnostic section of the device. As for the CO2 one, I have a WS-2902C device, and it reports a CO2 Battery level even though I don't have one either. I believe this is either a misnomer in the field as transmitted from the device or it's a big in the firmware.

If you still can't find the sensor, please set the add-on to log in DEBUG mode and provide logs. Please provide debug logs from the integration.

**Comment by tlskinneriv** [comment]
Closing this issue due to staleness. Please reopen if you're still experiencing issues.
