### ISSUE TITLE
awnet_local_data_<mac_address> as file name can't copy in Windows

### ISSUE THREAD

**Issue by heyitsyang** [tlskinneriv/awnet_local#26]
**Integration Version**: 
v1.1.1

**Home Assistant Version**:
2023.5.4

**Describe the bug**

The integration creates a file in the .storage directory whose filename is incompatible with the Windows filesystem due to use of colons ( : ) in the filename.  This prevents copying of this file using Windows as a mechanism for directly copying this file for backups and other purposes.  

**To Reproduce**

**Expected behavior**

Expected behavior is the ability to use Samba and other methods to copy the file using Windows

**Screenshots**

**Additional context**

**Debug log output from the integration (see Home Assistant docs for how to enable debug logging for an integration; integration name: "custom_components.awnet_local")**

```
Paste your logs here
```
![Screenshot 2023-06-09 161504](https://github.com/tlskinneriv/awnet_local/assets/14240918/5ed4af11-e837-4aab-92d4-71d0833bd8f1)

**Comment by tlskinneriv** [comment]
This is a legitimate usage that I simply had not thought of. Will work the fix into the next release. Thanks!
