### ISSUE TITLE
Last Rain unknown most of the time when it should be the last timestamp

### ISSUE THREAD

**Issue by tlskinneriv** [tlskinneriv/awnet_local#28]
**Integration Version**: 1.1.1

**Home Assistant Version**: 2023.6.1

**Describe the bug**
Last Rain sensor updating when it rains, but as soon as it's not raining, it becomes unknown. This is not the intended behavior. 

**Expected behavior**
Last Rain should stay the timestamp that it was last set to and restore on restart of HA.

**Comment by dlindnegm** [comment]
I'm seeing the same thing.  Currently running both the original and local versions side-by side on HASSOS.  Let me know if there's anything I can provide to assist.

**Comment by dlindnegm** [comment]
I'm not sure, but the "Lightning Strikes Last Hour" may have the same issue?  Mine shows as 'Unknown'.  The value for "Last Lightning Strike" accurately shows: Last Week -  June 5, 2023 at 4:45 PM.

**Comment by tlskinneriv** [comment]
Will check into the Lightning Strikes Last Hour. The Last Rain sensor issue is definitely a regression, but this other sensor may be affected by the same issue. Working it into the next release.

**Comment by uspino2** [comment]
> Will check into the Lightning Strikes Last Hour. The Last Rain sensor issue is definitely a regression, but this other sensor may be affected by the same issue. Working it into the next release.

I'm seeing the same thing with Lightning Strikes Last Hour. Very inconvenient: I use that sensor to cut off power to an external water pump that is prone to be hit by lightning. Please update us on this when you have a minute. thank You!

**Comment by knwpsk** [comment]
@tlskinneriv forgive me for commenting on this old ticket, and I'd happily open a new one if asked/told.

I just installed this integration yesterday. It's working GREAT... except I have this same problem: last_rain entity was automatically created by the integration, but it's always "unknown".  Has an old bug been re-introduced? or did I miss a config somehow?

FWIW, I artificially inserted the actual datetime of the last rain into the entity using DevTools, but in a few mins (the next time an input was received?) the entity value reverted to "unknown" again. 

What logs/etc can I provide?

**Comment by tlskinneriv** [comment]
Hi! This is a calculated sensor that depends on the date and hourly rain value being sent over by the weather station. If you just recently set up the integration and it has not rained since setup, then it will continue to report unknown until there is a change in the hourly rain value. 

If it has rained, and this value is still unknown, perhaps the weather station is sending a different name for the rain value that I'm not tracking. In this case, please place the add-on in at least INFO level for logging and send over the last request that the station sent through. Thanks!

**Comment by knwpsk** [comment]
OK thanks @tlskinneriv. Tonight when I get home I'll drop a bit of water in the collector and see if that works :)

(I tried force-changing the hourly_rain entity's value in HA > DevTools, but that didn't cause last_rain to recalculate. I'm assuming that doesn't engage the integration's code. Updates have to come through the mqtt interface to trigger a recalc?)
