### ISSUE TITLE
can't find my weather station

### ISSUE THREAD

**Issue by cybernard** [tlskinneriv/awnet_local#36]
**Integration Version**: 1.13

**Home Assistant Version**: newest 2023.7.3

Can not detect my device
I have a ws-5000 and an observer2 and neither is detected.

**To Reproduce**
Added the integration
filled in the station name and mac address 
click Ok
Got nothing
I tried turning on logging and got nothing it could not find the device.
It shows up on my ambient weather account.

**Expected behavior**
I was expecting it to find my device.

**Screenshots**
![image](https://github.com/tlskinneriv/awnet_local/assets/15042777/9412dd19-d071-4d7a-b1e8-0ec6e72ad92e)

**Additional context**

**Debug log output from the integration (see Home Assistant docs for how to enable debug logging for an integration; integration name: "custom_components.awnet_local")**
```
Paste your logs here
No logs found

Suggestion:
Why don't you let me add an IP address?  
Addendum can/will you support the observer2?

**Comment by tlskinneriv** [comment]
Have you set up the accompanying add-on mentioned in the Overview and Configuration sections of the README? https://github.com/tlskinneriv/hassio-addons/tree/master/awnet

Does the observer2 support sending the Ambient Weather protocol type calls to a custom server? If so, it would likely already work. If not, I'd need to know exactly what the API calls look like to be able to adjust the add-on to work properly. I do not have an observer2 to test with.

**Comment by cybernard** [comment]
Yes, the observer2, supports the upload to a custom server.  I went in and entered the IP of my homeassistant leaving everything else at the default.

Did the documentation change because the README you referenced only contains a section called "About".  I see nothing about overview or configuration in the README.

**Comment by tlskinneriv** [comment]
There is an "Installation" section below the "About" section at the link sent prior. There's also a [DOCS.md](https://github.com/tlskinneriv/hassio-addons/blob/master/awnet/DOCS.md) file in that directory that documents the configuration of the add-on and the station to have it work properly with the integration.

**Comment by tlskinneriv** [comment]
Were you able to get this set up? Has this issue been resolved?

**Comment by tlskinneriv** [comment]
In the event that this is still not working with your WS-5000/Observer2, please install the latest version of the add-on (1.0.1), which should have fixes for an issue where the request from the weather station is malformed. Please re-open this issue or open a new issue if the problem persists.

**Comment by cybernard** [comment]
I got this message back from ambient weather.

> Hello,
>  
> Thank you for following up.
> The method by which you are receiving data from the observer is not recommended.
> Therefore, we would not be releasing a firmware update to correct this issue.
> As we are not receiving any reports from customers using the proper method via API to connect to Home assistant.
> As, any change that is made would possibly affect the ability of other devices to report to Home assistant via API.
>

**Comment by cybernard** [comment]
GW3000B  The ecowitt can log locally into home assistant, and it picks up the ambient weather sensors.
So for now I am giving up on this isssue.

**Comment by tlskinneriv** [comment]
Did you try the 1.0.1 or greater version of the addon I mentioned in my last comment? If you have, can you set it to debug mode and send me the logs, please?

**Comment by cybernard** [comment]
The local device transmit extra data, and home assistant can't handle it.
So the data doesn't even reach your app to debug it.

**Comment by tlskinneriv** [comment]
You can point the weather station at Home Assistant, but you need to have the companion add-on setup and running for this integration to work properly. 

Link to add-on docs: https://github.com/tlskinneriv/hassio-addons/blob/master/awnet%2FDOCS.md

You'll need to point your weather station to your home assistant IP with the port that the add-on is listening on. If the weather station is set to point at the correct IP and port, the add-on will generate logs in DEBUG mode for any request that is made to it. 

If you can give me those debug logs, I can help understand why the integration isn't getting data.
