### ISSUE TITLE
WS-1550 Observer IP 2 Working 

### ISSUE THREAD

**Issue by MickPBduece** [tlskinneriv/awnet_local#39]
I have an Ambient WS-1550 and Ambient was able to get an Observer 2 IP device from Ambient that will run the 4.8.2 software.
Setup process was as expected 
Remove the old Observer and remove it's IP lease 
Install and configure the Observer 2 and Awnet software
Reset the WS-1550 
Delete the old WS device from the Ambient Accout and add the new device
Add the configuration to AWNET for the local connection
Install the add-on and integration and configure

**Comment by tlskinneriv** [comment]
Thank you for the report! README updated.
