### ISSUE TITLE
lifetime_rain Update

### ISSUE THREAD

**Issue by calanthe23** [tlskinneriv/awnet_local#44]
**Integration Version**: 
Latest

**Home Assistant Version**:
Core 2023.12.4
Supervisor 2023.12.0
Operating System 11.2
Frontend 20231208.2

**Describe the bug**
I noticed this warning in my logs today, and it requested that I open an issue here.

**Debug log output from the integration (see Home Assistant docs for how to enable debug logging for an integration; integration name: "custom_components.awnet_local")**
```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:851
First occurred: 2:22:04 PM (1 occurrences)
Last logged: 2:22:04 PM

Updating state for sensor.weather_main_controller_lifetime_rain (<class 'custom_components.awnet_local.sensor.AmbientWeatherSensor'>) took 0.513 seconds. Please create a bug report at https://github.com/tlskinneriv/awnet_local/issues
```

**Comment by tlskinneriv** [comment]
Has this warning occurred again? I would expect to see multiple sensors/binary_sensors have this issue since they are all updated at the same time. It's also possible to see this occur soon after an update. Are you seeing any other entries like this for other integrations? This usually indicates a performance issue if it's persistent.

**Comment by calanthe23** [comment]
It does not appear to have occurred again.  I was just following the instructions in the log, but if it's safe to ignore, I can do that going forward if it occurs again.  Let me know.  Thanks!

**Comment by tlskinneriv** [comment]
Likely safe to ignore for this one-off. Please reopen or open a new issue if it is recurring within a single start of HA. Thanks and Happy Holidays!
