### ISSUE TITLE
AWSNET No longer connected

### ISSUE THREAD

**Issue by mmartoccia** [tlskinneriv/awnet_local#47]
**Integration Version**: 

**Home Assistant Version**:

Core
2024.2.2
Supervisor
2024.02.0
Operating System
11.5
Frontend
20240207.1

**Describe the bug**
The system is not longer connecting. Cannot get it to reconnect. I am able to ping the AWS system by IP and the network is available just communications has stopped.

**To Reproduce**

No Logs produced.

**Comment by tlskinneriv** [comment]
Please take a look at #42 for details to see if you have the same issue. Please include debug logs from and the version of the AWNET add-on.

**Comment by mmartoccia** [comment]
Thank you! That worked and I'm back in business. Thanks for taking on this task and supporting this intergration!
