### ISSUE TITLE
Integration has ceased to function

### ISSUE THREAD

**Issue by JtwoA** [tlskinneriv/awnet_local#49]
**Integration Version**: 1.2.0

**Home Assistant Version**: 2024.5.5

**Describe the bug**
All sensors show "unavailable".  Reloading the integration has no effect.  Removed integration, readded integration, one device/one entity (instead of 20+ entities)

**To Reproduce**
1. Go to 'integration'
2. Click on 'reload'
3. Verified settings in AWN app
4. See error - no error.  No logs.  No... nothing.  

**Expected behavior**
Expectation is multiple sensors showing live data vs "unavailable"

**Screenshots**
![image](https://github.com/tlskinneriv/awnet_local/assets/12992040/33da3e12-ebd5-4be0-9be0-75b345ee4085)

**Additional context**

**Debug log output from the integration (see Home Assistant docs for how to enable debug logging for an integration; integration name: "custom_components.awnet_local")**
```
There are no log entries for this plugin when reloading it.
```
Debug log enabled, reloaded integration:
![image](https://github.com/tlskinneriv/awnet_local/assets/12992040/e80bba06-0e5a-4f1c-94a1-9614d76e2b97)

**Comment by tlskinneriv** [comment]
Please take a look at #42 for details to see if you have the same issue. Please include debug logs from and the version of the AWNET add-on.

**Comment by JtwoA** [comment]
> Please take a look at #42 for details to see if you have the same issue. Please include debug logs from and the version of the AWNET add-on.

I noted the version is 1.2.0 of the add-on.
#42 points to the MAC address format - this integration has been working flawlessly for many, many months.  Other than regular HA updates nothing has changed in the system.  This just stopped abruptly, which is very odd.  First question I always ask is "what changed" and I can't point to anything.

As for logs - I've enabled debug and reviewed the log output and see nothing pertaining to this add-on.  It's like it simply doesn't exist anymore.  Uninstalled, reinstalled (as noted) and it doesn't see any sensors any longer.

**Comment by tlskinneriv** [comment]
> I noted the version is 1.2.0 of the add-on.

That's the version of the integration. I'm looking for the version and debug logs from the [add-on](https://github.com/tlskinneriv/hassio-addons/tree/master/awnet). This can be found on the page for your add-ons in HA. 

> #42 points to the MAC address format - this integration has been working flawlessly for many, many months. 

#42 is about more than the format. It ultimately led to the discovery of a change in the data format sent by the weather station due to an update on the firmware. Specifically in [this comment](https://github.com/tlskinneriv/awnet_local/issues/42#issuecomment-1913357267) I overview an update to the add-on mentioned above to add an option to override the MAC sent by the station. This can cause the same symptoms as what you are facing. 

This integration works hand-in-hand with the add-on mentioned above to deliver the data to HA from the weather station. If both components are not configured and working properly, you won't get any data in HA. The debug logs from the add-on are critical to troubleshooting further since there are no errors in the HA logs.

**Comment by JtwoA** [comment]
> > I noted the version is 1.2.0 of the add-on.
> 
> That's the version of the integration. I'm looking for the version and debug logs from the [add-on](https://github.com/tlskinneriv/hassio-addons/tree/master/awnet). This can be found on the page for your add-ons in HA.
> 
> > #42 points to the MAC address format - this integration has been working flawlessly for many, many months.
> 
> #42 is about more than the format. It ultimately led to the discovery of a change in the data format sent by the weather station due to an update on the firmware. Specifically in [this comment](https://github.com/tlskinneriv/awnet_local/issues/42#issuecomment-1913357267) I overview an update to the add-on mentioned above to add an option to override the MAC sent by the station. This can cause the same symptoms as what you are facing.
> 
> This integration works hand-in-hand with the add-on mentioned above to deliver the data to HA from the weather station. If both components are not configured and working properly, you won't get any data in HA. The debug logs from the add-on are critical to troubleshooting further since there are no errors in the HA logs.

I had completely missed that this is an add-on/integration combo.  

Add-on version is 1.1.1

**Comment by JtwoA** [comment]
> > > I noted the version is 1.2.0 of the add-on.
> > 
> > 
> > That's the version of the integration. I'm looking for the version and debug logs from the [add-on](https://github.com/tlskinneriv/hassio-addons/tree/master/awnet). This can be found on the page for your add-ons in HA.
> > > #42 points to the MAC address format - this integration has been working flawlessly for many, many months.
> > 
> > 
> > #42 is about more than the format. It ultimately led to the discovery of a change in the data format sent by the weather station due to an update on the firmware. Specifically in [this comment](https://github.com/tlskinneriv/awnet_local/issues/42#issuecomment-1913357267) I overview an update to the add-on mentioned above to add an option to override the MAC sent by the station. This can cause the same symptoms as what you are facing.
> > This integration works hand-in-hand with the add-on mentioned above to deliver the data to HA from the weather station. If both components are not configured and working properly, you won't get any data in HA. The debug logs from the add-on are critical to troubleshooting further since there are no errors in the HA logs.
> 
> I had completely missed that this is an add-on/integration combo.
> 
> Add-on version is 1.1.1

And the MAC address override did it.  (I did have the ALL CAPS issue but saw that noted later in #42's comments.)

There was a new firmware pushed to these and I don't recall for certain if I pushed that before or after the data stoppage.

Thanks VERY much!  We're good to close here.
