### ISSUE TITLE
Help with Set-Up

### ISSUE THREAD

**Issue by EAuckland** [tlskinneriv/awnet_local#52]
**Integration Version**: 1.2.0

**Home Assistant Version**:2024.9.3

**Describe the bug**
I want to make this clear, this is not your issue, it is mine. Haha. Your integration has been working for me perfectly however the display I had it set up on took a dump over the weekend. I tried setting it up on another display (Same WS-5000) however I can't get it to work.
Here is a screen shot of my awnet screen.

![Screenshot_20240930-091539](https://github.com/user-attachments/assets/6b21f514-9508-4677-a363-6fa90e89dc18)

**Comment by tlskinneriv** [comment]
Hi! Did you end up figuring this out or are you still looking for guidance?

**Comment by EAuckland** [comment]
> Hi! Did you end up figuring this out or are you still looking for guidance?

Yes I did, all my fault. Thank you!
